### ISSUE TITLE
时间戳的表示似乎不够统一？

### ISSUE THREAD

**Issue by artiga033** [KarinJS/kritor#11]
https://github.com/KarinJS/kritor/blob/27669a8f5704a8876658a47cc976f1fb3e9cc2f4/protos/common/message_data.proto#L20
https://github.com/KarinJS/kritor/blob/27669a8f5704a8876658a47cc976f1fb3e9cc2f4/protos/guild/guild.proto#L122
https://github.com/KarinJS/kritor/blob/27669a8f5704a8876658a47cc976f1fb3e9cc2f4/protos/guild/guild_data.proto#L66

以上之类地方的时间戳数据格式都不相同，这是有意为之还是意外？

以及文档中似乎没有明确说明时间戳单位是秒还是毫秒，这对于不了解QQ协议的人而言略显困惑(

**Comment by sj817** [comment]
`uint32`，频道这边照搬`shamrock`过来的，可能很多错误，因为目前频道的情况过于迷糊，不太考虑关注频道这边。

**Comment by Simplxss** [comment]
单位为秒 频道暂时没做太多考虑（tx自己都不要的东西了）

**Comment by Simplxss** [comment]
现在统一为uint64了, 原来的也兼容(2038年前)
