### ISSUE TITLE
help: 在使用python时因为循环依赖无法导入包

### ISSUE THREAD

**Issue by brokestar233** [KarinJS/kritor#2]
event和message相互依赖，导致了无论先加载哪个都会导致报错
![8e0a4817f2a63e9b6d110797eb771cc3](https://github.com/KarinJS/kritor/assets/161171586/5e2f3198-7210-4a8e-91ed-2359ed50d283)

**Comment by Simplxss** [comment]
啊? 那几个文件?

**Comment by Simplxss** [comment]
看下代码怎么写的

**Comment by brokestar233** [comment]
`__init__.py`全是这样写的，主文件就只有import src
![image](https://github.com/KarinJS/kritor/assets/161171586/51849be3-8723-49c1-89a1-c405513e7901)

文件结构
![image](https://github.com/KarinJS/kritor/assets/161171586/98f64d67-c878-4d9d-956e-c08f1b10cd40)

**Comment by brokestar233** [comment]
> 啊?那几个文件?

message_pb2和event_pb2

**Comment by Simplxss** [comment]
测试一下, 应该已经修复了. 现在把原来的部分定义拆分到common里面, 让common作为message和event的依赖了

**Comment by brokestar233** [comment]
> 测试一下, 应该已经修复了.现在把原来的部分定义拆分到common里面， 让common作为message和event的依赖了

现在可以了
