### ISSUE TITLE
有考虑过写个简单的入门教程吗（

### ISSUE THREAD

**Issue by Miuzarte** [KarinJS/kritor#6]
没有discussion直接开issue了🙏，折腾了半天没弄懂哪里有问题

![image](https://github.com/KarinJS/kritor/assets/66856838/e71e3a7e-9d53-4ee1-9a60-b6efadc76ab4)
![image](https://github.com/KarinJS/kritor/assets/66856838/bea22fd1-8dd4-45c8-8226-5e5c6ccae15b)

**Comment by Simplxss** [comment]
已修复
