### ISSUE TITLE
常量与结构体重名

### ISSUE THREAD

**Issue by Miuzarte** [KarinJS/kritor#7]
[message_element.pb.go](https://github.com/KarinJS/kritor/files/14903497/message_element.pb.go.json)
![image](https://github.com/KarinJS/kritor/assets/66856838/4eff3f8d-9b62-45a9-936e-87b13b65c820)
![image](https://github.com/KarinJS/kritor/assets/66856838/ccc639d8-670f-45d3-a0c2-5d8c5b169da8)

**Comment by Simplxss** [comment]
常量已改全大写
