### ISSUE TITLE
是否考虑提供一个静态站点以便于下载 proto 文件和提供changelog

### ISSUE THREAD

**Issue by ForteScarlet** [KarinJS/kritor#8]
比如用 GitHub Pages 之类的，以及如果发生变动的话的变更细节（changelog）

_或者在 releases 里随版本发布一个打包文件之类的_

**Comment by Simplxss** [comment]
现在还在制定阶段 变动会较大 文档也没完善 暂时不会建网站 之后可能会写一个网页
预计这周末协议就能基本定型 到时会发版prerelease 往后应该就不会有大范围变更了 changelog肯定会有的

**Comment by ForteScarlet** [comment]
好的，了解了，期待定型。

_~之前写了一大半，今天再来一看变了一片两眼一黑了~_
